name: Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Mostrar estrutura de diretórios
      run: |
        pwd
        ls -la
        ls -la sistema-tarefas-logistica || echo "Pasta sistema-tarefas-logistica não existe"

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Rodar testes
      run: npm test

    - name: Mostrar estrutura de diretórios
  run: |
    pwd
    ls -la
    ls -la sistema-tarefas-logistica || echo "Pasta sistema-tarefas-logistica não existe"