name: Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Mostrar estrutura de diretórios na raiz
      run: |
        pwd
        ls -la

    - name: Mostrar estrutura de diretórios na pasta sistema-tarefas-logistica
      run: |
        ls -la sistema-tarefas-logistica

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install
      working-directory: sistema-tarefas-logistica

    - name: Rodar testes
      run: npm test
      working-directory: sistema-tarefas-logistica